src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $from_email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $to_email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_subject;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_message;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_created;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFromEmail(): ?string
    {
        return $this->from_email;
    }

    public function setFromEmail(?string $from_email): self
    {
        $this->from_email = $from_email;

        return $this;
    }

    public function getToEmail(): ?string
    {
        return $this->to_email;
    }

    public function setToEmail(?string $to_email): self
    {
        $this->to_email = $to_email;

        return $this;
    }

    public function getEmailSubject(): ?string
    {
        return $this->email_subject;
    }

    public function setEmailSubject(?string $email_subject): self
    {
        $this->email_subject = $email_subject;

        return $this;
    }

    public function getEmailMessage(): ?string
    {
        return $this->email_message;
    }

    public function setEmailMessage(?string $email_message): self
    {
        $this->email_message = $email_message;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(?\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>
      {% block title %}
        Welcome!
      {% endblock %}
    </title>
    {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}

    {% block stylesheets %}
      {# {{ encore_entry_link_tags('app') }} #}
      <link rel="stylesheet"
        href="https://bootswatch.com/5/cosmo/bootstrap.min.css" />

      <link href="/css/styles.css" rel="stylesheet" />
    {% endblock %}

    {% block javascripts %}
      {# {{ encore_entry_script_tags('app') }} #}

      <script type="text/javascript"
        src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
      <script type="text/javascript" src="js/main.js"></script>
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% endblock %}

    {% include 'contactInfoModal.html.twig' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
      crossorigin="anonymous"></script>
  </body>
</html>

templates/contactInfoModal.html.twig
<!-- Modal -->
<div class="modal fade"
  id="infoModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Kontakt Info
        </h5>
        <button type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close">

        </button>
      </div>
      <div class="modal-body" id="info-content"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>

templates/contacts.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Hello Test Title
{% endblock %}
{% block body %}
<div class="container">
<div class="row flex-nowrap">
   <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark" style="min-width: 235px;">
      <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
         <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
         <span class="fs-5 d-none d-sm-inline">tecnoConcept</span>
         </a>
         {% include "navigation.html.twig" %}
         <hr>
      </div>
   </div>

   <div class="col py-3 content px-4" style="overflow: auto;">
      <div class="formular mt-4 ">
         <h3 class="mb-5">Gespeicherte E-Mails</h3>
         <form class="row g-3">
         <div class="row">
            <div class="col">
               <h6>EMAILS</h6>
            </div>
            <div class="col">
               <button type="button" style="float:right" onclick="deleteOlderThan2Weeks()"  class="btn btn-warning">Delete Older Than 2 Weeks</button>
            </div>
         </div>
         <hr>
         <div class="col-md-12">
            <div class="table-responsive">
               <table class="table table-striped">
                  <thead>
                     <tr>
                        <th scope="col">#</th>
                        <th scope="col">Vorname</th>
                        <th scope="col">Nachname</th>
                        <th scope="col">To</th>
                        <th scope="col">Subject</th>
                        <th scope="col">Date Send</th>
                        <th scope="col">...</th>
                     </tr>
                  </thead>
                  <tbody id="table-data">
                     {% for contact in contacts %}
                     <tr>
                           <td class="align-middle"> {{contact.id}} </td>
                           <td class="align-middle"> {{contact.firstname}} </td>
                           <td class="align-middle"> {{contact.lastname}} </td>
                           <td class="align-middle"> {{contact.toEmail}} </td>
                           <td class="align-middle"> {{contact.emailSubject}} </td>
                           <td class="align-middle" style="width:100px">
                           {{ contact.dateCreated | date('d.m.Y') }}
                        </td>
                        <td class="align-middle">      
                           <button type="button" class="btn btn-primary" onclick="getContactInfo({{contact.id}})"/>Show</button>
                           <button type="button" class="btn btn-danger" onclick="deleteContact({{contact.id}})"/>Delete</button>
                        </td>
                        </tr>
                     {% endfor %}
                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>
</div>


{% endblock %}

templates/contactsData.html.twig
{% for contact in contacts %}
<tr>
    <td class="align-middle"> {{contact.id}} </td>
    <td class="align-middle"> {{contact.firstname}} </td>
    <td class="align-middle"> {{contact.lastname}} </td>
    <td class="align-middle"> {{contact.toEmail}} </td>
    <td class="align-middle"> {{contact.emailSubject}} </td>
    <td class="align-middle" style="width:100px">
    {{ contact.dateCreated | date('d.m.Y') }}
</td>
<td class="align-middle">      
    <button type="button" class="btn btn-primary" onclick="getContactInfo({{contact.id}})"/>Show</button>
    <button type="button" class="btn btn-danger" onclick="deleteContact({{contact.id}})"/>Delete</button>
</td>
</tr>
{% endfor %}

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Hello Test Title
{% endblock %}
{% block body %}
<div class="container">
<div class="row flex-nowrap">
   <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark" style="min-width: 235px;">
      <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
         <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
         <span class="fs-5 d-none d-sm-inline">tecnoConcept</span>
         </a>
         {% include "navigation.html.twig" %}
         <hr>
      </div>
   </div>
   <div class="col py-3 content px-4" style="overflow: auto;">
      <div class="formular mt-4 ">
         <h3 class="mb-5">Kontaktformular</h3>
         <form onsubmit="submitData(this, event)" class="row g-3">
            <h6>SMTP CONFIG</h6>
            <hr>
            <div class="col-md-6">
               <label for="inputCity" class="form-label">SMTP server address</label>
               <input type="text" class="form-control" placeholder="smtp.gmail.com" id="smtpAdress" value="" required>
            </div>
            <div class="col-md-6">
               <label for="inputCity" class="form-label">SMTP port</label>
               <input type="text" class="form-control" placeholder="465" id="smtpPort" value="25" required>
            </div>
            <div class="col-md-6">
               <label for="inputCity" class="form-label">SMTP username</label>
               <input type="text" class="form-control" placeholder="you@gmail.com" id="smtpUsername" value="" required>
            </div>
            <div class="col-md-6">
               <label for="inputCity" class="form-label">SMTP password</label>
               <input type="password" class="form-control" placeholder="fh1YKg24grASMOD" id="smtpPassword" value="" required>
            </div>
            <h6 class="mt-5">MESSAGE</h6>
            <hr>
            <div class="col-md-6">
               <label for="inputEmail4" class="form-label">Name</label>
               <input type="text" class="form-control" id="name" required>
            </div>
            <div class="col-md-6">
               <label for="inputPassword4" class="form-label">Nachname</label>
               <input type="text" class="form-control" id="nachname" required>
            </div>
            <div class="col-md-6">
               <label for="inputEmail4" class="form-label">From:</label>
               <input type="email" class="form-control" id="email" value="" required>
            </div>
            <div class="col-md-6">
               <label for="inputEmail4" class="form-label">To:</label>
               <input type="email" class="form-control" id="to_email" value="" required>
            </div>
            <div class="col-md-12">
               <label for="inputEmail4" class="form-label">Subject</label>
               <input type="text" class="form-control" id="subject" placeholder="Subject" required>
            </div>
            <div class="col-12">
               <label for="exampleFormControlTextarea1" class="form-label">Message</label>
               <textarea class="form-control" id="message" rows="3" required></textarea>
            </div>
            <div class="col-12">
               <button type="submit" class="float-end btn btn-primary">Senden</button>
            </div>
         </form>
      </div>


    {% include "indexModals.html.twig" %}


   </div>
</div>
{% endblock %}

templates/indexModals.html.twig
<!-- Modal -->
<div class="modal fade"
  id="modalLoading"
  tabindex="-1"
  aria-labelledby="modalLoading"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content border-0" style="background-color: transparent;">
      <div class="d-flex justify-content-center">
        <div class="spinner-border" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-backdrop fade show"
    id="backdrop"
    style="display: none;"></div>
</div>

<!-- Modal -->
<div class="modal fade"
  id="successModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Vielen Dank!
        </h5>
        <button type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close">

        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-4" style="text-align: center;">
            <img style="width: 100px;" src="/images/success-icon.png" alt="" />
          </div>
          <div class="col-8">
            <p>
              Ihre Nachricht wurde versendet.
            </p>
            <p>
              Wir werden uns so bald wie möglich mit Ihnen in Verbindung setzen.
            </p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button"
          class="btn btn-secondary"
          data-bs-dismiss="modal"
          onclick="window.location.href = '/'">
          Schließen
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade"
  id="failModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Fehlrgeschlagen
        </h5>
        <button type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close">

        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-4" style="text-align: center;">
            <img style="width: 100px;" src="/images/fail-icon.png" alt="" />
          </div>
          <div class="col-8">
            <p>
              Ihre Nachricht konnte nicht versendet.
            </p>
            <p>
              Bitte versuchen Sie es später noch einmal.
            </p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button"
          class="btn btn-secondary"
          data-bs-dismiss="modal"
          onclick="window.location.href = '/'">
          Schließen
        </button>
      </div>
    </div>
  </div>
</div>

templates/navigation.html.twig
<ul class="nav nav-pills flex-column mb-auto">
  <li class="nav-item">
    <a href="/"
      class="nav-link text-white {% if path == "index" %} active {% endif %}"
      aria-current="page">
      Kontaktformular
      

    </a>
  </li>

  <li>
    <a href="/contacts"
      class="nav-link text-white {% if path == "contacts" %} active {% endif %}">
      Gespeicherte Emails
    </a>
  </li>
</ul>